CREATE DATABASE ReceiptHub 
USE ReceiptHub


CREATE TABLE users (
  id INT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt DATE DEFAULT CURRENT_TIMESTAMP
);

